// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0OdedSxUg5xgsFRwRoXNckhL_0u1NXc4',
    appId: '1:542374342901:web:6df9f433f6c18e01eed5bc',
    messagingSenderId: '542374342901',
    projectId: 'ocean-cleanup-f6d22',
    authDomain: 'ocean-cleanup-f6d22.firebaseapp.com',
    storageBucket: 'ocean-cleanup-f6d22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO4da1N8gS3epGD1P6ab7MK0ZWYfSxUVA',
    appId: '1:542374342901:android:93b052857170fffbeed5bc',
    messagingSenderId: '542374342901',
    projectId: 'ocean-cleanup-f6d22',
    storageBucket: 'ocean-cleanup-f6d22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe9m8tlY2EryuaTb4rB0EOXaY6iVvXzl4',
    appId: '1:542374342901:ios:2dba52d93e5ad725eed5bc',
    messagingSenderId: '542374342901',
    projectId: 'ocean-cleanup-f6d22',
    storageBucket: 'ocean-cleanup-f6d22.appspot.com',
    iosBundleId: 'com.gamejam.oceancleanup.oceanCleanup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe9m8tlY2EryuaTb4rB0EOXaY6iVvXzl4',
    appId: '1:542374342901:ios:bc93a6dbb2662cf8eed5bc',
    messagingSenderId: '542374342901',
    projectId: 'ocean-cleanup-f6d22',
    storageBucket: 'ocean-cleanup-f6d22.appspot.com',
    iosBundleId: 'com.gamejam.oceancleanup.oceanCleanup.RunnerTests',
  );
}
